server:
  port: 8087
  forward-headers-strategy: framework

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3311/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${PAYMENT_DB_USER:payment_user}
    password: ${PAYMENT_DB_PASS:payment_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_T6IweRxRewEjzh}
  key-secret: ${RAZORPAY_KEY_SECRET:6PcjN78QbeqtaFxZBjSYffqh}

user:
  service:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

