spring.application.name=ai-service
spring.datasource.url=jdbc:postgresql://localhost:5432/meetingroomdb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2