spring.application.name=localyze

spring.datasource.url=jdbc:postgresql://localhost:5432/localyze
spring.datasource.username=postgres
spring.datasource.password=yoges
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect