
# ==========================
# Server
# ==========================
server.port=8081

# ==========================
# Application
# ==========================
spring.application.name=auth-service

# ==========================
# MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/localyze_auth
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Eureka
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==========================
# Actuator
# ==========================
management.endpoints.web.exposure.include=health,info

# ==========================
# Swagger
# ==========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Jwt
# ==========================

jwt.secret=F7cP8nQ2Lm5XzV9AaH4KsY1RwU6TdE3BjM8NpL0QxW7ErC5VyZ2GhI9JkS4DnP6

jwt.expiration=86400000
jwt.refresh-expiration=604800000
# ==========================
# debuggin
# ==========================

logging.level.org.springframework.security=TRACE